In [7]:
### Numpy-->Play with arrays(numbers)
###pandas -->dataset
### Matplotlib-->data visualization
### Seaborn -->data visualisation
### Scipy--> statistical
### Sklearn-->algorithms

# NUMPY:PACKAGE FOR MULTIDIMENTIONAL ARRAY

In [8]:
import numpy as np

In [9]:
simple_list=[6,7,9]
np.array(simple_list)

array([6, 7, 9])

In [10]:
arr=np.array([1,2,3])
arr

array([1, 2, 3])

In [11]:
lists_of_lists=[[1,2,3],[4,5,6],[7,8,9]]
np.array(lists_of_lists)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
np.arange(1,20)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [13]:
np.arange(1,9)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [14]:
np.arange(1,100)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [15]:
np.arange(1,20,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [16]:
np.arange(1,20,3)

array([ 1,  4,  7, 10, 13, 16, 19])

In [17]:
np.arange(1,36,5)

array([ 1,  6, 11, 16, 21, 26, 31])

In [18]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [19]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [20]:
np.zeros(10,int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [21]:
np.ones(10,int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [22]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [23]:
np.ones((2,3),int)

array([[1, 1, 1],
       [1, 1, 1]])

In [24]:
np.ones(100)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [25]:
np.linspace(0,2,5)

array([0. , 0.5, 1. , 1.5, 2. ])

In [26]:
np.linspace(0,20,8)

array([ 0.        ,  2.85714286,  5.71428571,  8.57142857, 11.42857143,
       14.28571429, 17.14285714, 20.        ])

In [27]:
np.eye(10,dtype=int)

array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1]])

In [28]:
np.eye(20,dtype=int)

array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0,

In [29]:
np.random.rand(3,5)

array([[0.19973437, 0.90707129, 0.34042183, 0.09749993, 0.39127689],
       [0.95185725, 0.45882491, 0.78464838, 0.82958778, 0.52689443],
       [0.6919572 , 0.36711402, 0.28609568, 0.36801355, 0.52882126]])

In [30]:
arr=np.random.randn(2,4)
arr

array([[ 0.9138829 ,  0.95519626,  0.17012149, -0.49799172],
       [ 0.19419234,  0.45787592,  0.945396  , -0.23594497]])

In [31]:
np.random.randint(2,16)

11

In [32]:
np.random.randint(20,56,100)

array([31, 21, 43, 40, 27, 26, 21, 39, 39, 29, 41, 25, 38, 50, 42, 37, 23,
       49, 40, 46, 54, 46, 44, 39, 25, 24, 20, 24, 47, 25, 22, 41, 38, 21,
       41, 37, 32, 32, 29, 28, 29, 47, 36, 46, 39, 31, 25, 21, 43, 35, 34,
       22, 29, 21, 48, 51, 25, 30, 25, 21, 55, 38, 31, 39, 50, 23, 20, 24,
       47, 34, 54, 44, 45, 49, 47, 20, 44, 47, 51, 26, 31, 37, 20, 36, 34,
       50, 21, 27, 26, 23, 40, 37, 22, 35, 40, 34, 35, 25, 35, 47])

In [33]:
sample_array=np.arange(30)
sample_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [34]:
rand_array=np.random.randint(0,10,50)
rand_array

array([5, 2, 6, 4, 5, 9, 6, 7, 0, 9, 3, 6, 6, 0, 7, 9, 2, 1, 9, 7, 7, 1,
       7, 0, 9, 2, 0, 1, 4, 0, 8, 1, 6, 6, 5, 9, 7, 2, 3, 3, 6, 8, 9, 6,
       1, 9, 6, 6, 2, 7])

In [35]:
sample_array.reshape(6,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [36]:
sample_array.reshape(5,5)

ValueError: cannot reshape array of size 30 into shape (5,5)

In [37]:
sample_array.reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [38]:
rand_array.max()

9

In [42]:
rand_array.argmax()

5

In [45]:
a=np.eye(5)
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [46]:
a.T

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [49]:
a=np.random.rand(2,3)
a

array([[0.57775334, 0.08181974, 0.41533906],
       [0.64960024, 0.3397018 , 0.50194723]])

In [50]:
a.T

array([[0.57775334, 0.64960024],
       [0.08181974, 0.3397018 ],
       [0.41533906, 0.50194723]])

In [51]:
sample_array=np.arange(10,21)
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [52]:
sample_array[0]

10

In [53]:
sample_array[2:5]

array([12, 13, 14])

In [54]:
sample_array[1:4]=100

In [55]:
sample_array

array([ 10, 100, 100, 100,  14,  15,  16,  17,  18,  19,  20])

In [56]:
sample_array=np.arange(10,21)
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [57]:
sample_array[0:7]

array([10, 11, 12, 13, 14, 15, 16])

In [58]:
subset_sample_array=sample_array[0:7]
subset_sample_array

array([10, 11, 12, 13, 14, 15, 16])

In [59]:
subset_sample_array[:]=1001
subset_sample_array

array([1001, 1001, 1001, 1001, 1001, 1001, 1001])

# TWO-DIMENTIONAL ARRAY

In [60]:
import numpy as np


In [61]:
sample_matrix=np.array([[50,20,1,23],[24,23,21,33],[56,76,24,7]])
sample_matrix

array([[50, 20,  1, 23],
       [24, 23, 21, 33],
       [56, 76, 24,  7]])

In [62]:
sample_matrix[1,2]

21

In [63]:
sample_matrix[2,:]

array([56, 76, 24,  7])

In [64]:
sample_matrix[2]

array([56, 76, 24,  7])

In [65]:
sample_matrix[:,(3,2)]

array([[23,  1],
       [33, 21],
       [ 7, 24]])

# selection techniques

In [66]:
sample_array=np.arange(1,20)

In [67]:
sample_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [68]:
sample_array+sample_array

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38])

In [69]:
np.exp(sample_array)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04, 5.98741417e+04, 1.62754791e+05,
       4.42413392e+05, 1.20260428e+06, 3.26901737e+06, 8.88611052e+06,
       2.41549528e+07, 6.56599691e+07, 1.78482301e+08])

In [70]:
np.sqrt(sample_array)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766,
       3.31662479, 3.46410162, 3.60555128, 3.74165739, 3.87298335,
       4.        , 4.12310563, 4.24264069, 4.35889894])

In [71]:
np.log(sample_array)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509,
       2.39789527, 2.48490665, 2.56494936, 2.63905733, 2.7080502 ,
       2.77258872, 2.83321334, 2.89037176, 2.94443898])

In [72]:
np.max(sample_array)

19

In [73]:
np.min(sample_array)

1

In [74]:
np.argmax(sample_array)

18

In [75]:
np.argmin(sample_array)

0

In [76]:
np.square(sample_array)

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144, 169,
       196, 225, 256, 289, 324, 361])

In [77]:
np.std(sample_array)

5.477225575051661

In [78]:
np.var(sample_array)

30.0

In [79]:
np.mean(sample_array)

10.0

In [81]:
array=np.random.randn(3,4)
array

array([[ 1.60317278, -0.83647052,  0.63126696,  0.68943064],
       [-1.86459618,  1.78920921, -0.02084743,  0.20630068],
       [ 0.44829213, -0.35002255, -0.22701919,  1.15437396]])

In [82]:
np.round(array,decimals=2)

array([[ 1.6 , -0.84,  0.63,  0.69],
       [-1.86,  1.79, -0.02,  0.21],
       [ 0.45, -0.35, -0.23,  1.15]])

In [83]:
sports=np.array(['golf','cricket','fball','cricket'])

In [84]:
np.unique(sports)

array(['cricket', 'fball', 'golf'], dtype='<U7')

# Pandas

In [85]:
import pandas as pd
import numpy as np

# pandas dataframe and indexing

In [88]:
sports1=pd.Series([1,2,3,4],index=['cricket','football','basketball','golf'])
sports1

cricket       1
football      2
basketball    3
golf          4
dtype: int64

In [89]:
sports1['football']

2

In [90]:
sports2=pd.Series([11,2,3,4],index=['cricket','football','baseball','golf'])
sports2

cricket     11
football     2
baseball     3
golf         4
dtype: int64

In [91]:
sports1+sports2

baseball       NaN
basketball     NaN
cricket       12.0
football       4.0
golf           8.0
dtype: float64

In [99]:
df1=pd.DataFrame(np.random.rand(8,5),index='A B C D E F G H'.split(),columns='Score1 Score2 Score3 Score4 Score5'.split())
df1

Score1    Score2    Score3    Score4    Score5
A  0.739300  0.448160  0.759248  0.337273  0.052103
B  0.269060  0.406929  0.750679  0.575195  0.782598
C  0.074324  0.101342  0.518794  0.759155  0.674855
D  0.178287  0.261043  0.077796  0.895238  0.759554
E  0.495592  0.560511  0.629345  0.665426  0.800692
F  0.226600  0.598794  0.173120  0.220831  0.784868
G  0.971488  0.628970  0.262925  0.721724  0.078634
H  0.071233  0.056018  0.165147  0.518229  0.333970

In [100]:
df1["Score1"]

A    0.739300
B    0.269060
C    0.074324
D    0.178287
E    0.495592
F    0.226600
G    0.971488
H    0.071233
Name: Score1, dtype: float64

In [101]:
df1[["Score1","Score2"]]

Score1    Score2
A  0.739300  0.448160
B  0.269060  0.406929
C  0.074324  0.101342
D  0.178287  0.261043
E  0.495592  0.560511
F  0.226600  0.598794
G  0.971488  0.628970
H  0.071233  0.056018

In [102]:
df1['Score6']=df1['Score1']+df1['Score2']
df1

Score1    Score2    Score3    Score4    Score5    Score6
A  0.739300  0.448160  0.759248  0.337273  0.052103  1.187459
B  0.269060  0.406929  0.750679  0.575195  0.782598  0.675989
C  0.074324  0.101342  0.518794  0.759155  0.674855  0.175666
D  0.178287  0.261043  0.077796  0.895238  0.759554  0.439330
E  0.495592  0.560511  0.629345  0.665426  0.800692  1.056103
F  0.226600  0.598794  0.173120  0.220831  0.784868  0.825395
G  0.971488  0.628970  0.262925  0.721724  0.078634  1.600458
H  0.071233  0.056018  0.165147  0.518229  0.333970  0.127251

In [103]:
df2={'ID':['101','102','103','107','176'],'Name':['John','dhruthi','haneesh','anitha','venkata'],'Profit':[20,54,58,34,387]}
df=pd.DataFrame(df2)
df

ID     Name  Profit
0  101     John      20
1  102  dhruthi      54
2  103  haneesh      58
3  107   anitha      34
4  176  venkata     387

In [104]:
df["ID"]

0    101
1    102
2    103
3    107
4    176
Name: ID, dtype: object

In [105]:
df[["ID","Name"]]

ID     Name
0  101     John
1  102  dhruthi
2  103  haneesh
3  107   anitha
4  176  venkata

In [106]:
df=df.drop("ID",axis=1)

In [107]:
df

Name  Profit
0     John      20
1  dhruthi      54
2  haneesh      58
3   anitha      34
4  venkata     387

In [108]:
df.drop(3)

Name  Profit
0     John      20
1  dhruthi      54
2  haneesh      58
4  venkata     387